import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Providers } from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}  className="min-h-screen bg-gray-100 border border-black`}>
       <Providers>
        <Navbar/>
       <main>{children}</main> 
       <footer className="bg-gray-800 text-white text-center py-6 mt-10">
        <p className="text-sm">© 2025 StructX. All rights reserved.</p>
      </footer>
      </Providers>
      </body>
    </html>
  );
}
